### ISSUE TITLE
Shortcuts do not register on Windows 8 or Kali Linux

### ISSUE THREAD

**Issue by MelbGitHubGuy** [tulskiy/jkeymaster#23]
Great library. Works perfect on my Mac OSX and Windows 7. Unfortunately it does not register on my Windows 8 32-bit, or Kali Linux.

Linux error is as follows:

INFO: Starting X11 global hotkey provider
Exception in thread "Thread-3" java.lang.UnsatisfiedLinkError: Can't obtain updateLastError method for class com.sun.jna.Native
	at com.sun.jna.Native.initIDs(Native Method)
	at com.sun.jna.Native.<clinit>(Native.java:139)
	at com.tulskiy.keymaster.x11.X11.<clinit>(X11.java:31)
	at com.tulskiy.keymaster.x11.X11Provider$1.run(X11Provider.java:54)
	at java.lang.Thread.run(Thread.java:745)

**Comment by rimrim** [comment]
Yes really great but not working on Windows 8 64-bit neither, please fix or give a clue how to do it ;)

**Comment by tulskiy** [comment]
@mrjayway, sorry for late response. your problem on Kali Linux seems to be that you have an older version of jna installed on classpath. Try adding `-Djna.nosys=true` to vm args. See https://github.com/twall/jna/issues/281

I will try to see how the library works on win 8 once I can get my hands on one :)

**Comment by tulskiy** [comment]
are you guys running win 8 or 8.1? I just tried in win 8 VM and everything works fine for me. I will need some logs

**Comment by rimrim** [comment]
I'm running 8.1 and I should say only "Windows" key combination not working. Cheers

**Comment by rimrim** [comment]
Hi, and I've just tried on ubuntu 14.04 as well, same problem, the combination of "Windows" + something, not working. Thanks

**Comment by JBarna** [comment]
Just wanted to drop a line and say that this worked for me on windows 10
