### ISSUE TITLE
error on Win10/x86_64/jdk8/jna 5.2.0

### ISSUE THREAD

**Issue by jjYBdx4IL** [tulskiy/jkeymaster#32]
Getting the following error when trying to set up the provider as described in the README:

17:33:58 [Thread-1] INFO WindowsProvider - Starting Windows global hotkey provider
Exception in thread "Thread-1" java.lang.IllegalArgumentException: Invalid Structure field in class com.tulskiy.keymaster.windows.User32$MSG, field name 'wParam' (class com.tulskiy.keymaster.windows.User32$Parameter): The type "com.tulskiy.keymaster.windows.User32$Parameter" is not supported: Can't create an instance of class com.tulskiy.keymaster.windows.User32$Parameter, requires a public no-arg constructor: java.lang.reflect.InvocationTargetException
	at com.sun.jna.Structure.validateField(Structure.java:1214)
	at com.sun.jna.Structure.validateFields(Structure.java:1223)
	at com.sun.jna.Structure.<init>(Structure.java:200)
	at com.sun.jna.Structure.<init>(Structure.java:193)
	at com.sun.jna.Structure.<init>(Structure.java:180)
	at com.sun.jna.Structure.<init>(Structure.java:172)
	at com.tulskiy.keymaster.windows.User32$MSG.<init>(User32.java:54)
	at com.tulskiy.keymaster.windows.WindowsProvider$1.run(WindowsProvider.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: The type "com.tulskiy.keymaster.windows.User32$Parameter" is not supported: Can't create an instance of class com.tulskiy.keymaster.windows.User32$Parameter, requires a public no-arg constructor: java.lang.reflect.InvocationTargetException
	at com.sun.jna.Native.getNativeSize(Native.java:1356)
	at com.sun.jna.Structure.getNativeSize(Structure.java:2172)
	at com.sun.jna.Structure.getNativeSize(Structure.java:2162)
	at com.sun.jna.Structure.validateField(Structure.java:1210)
	... 8 more

**Comment by jjYBdx4IL** [comment]
a lot of what jkeymaster added at the JNA level is now included with jna 5.4.0. Fixing this should be doable by simply removing code.
